alias PetClinic.Repo
alias PetClinic.PetClinicService.Pet
alias PetClinic.PetClinicService.Owner
alias PetClinic.PetHealthExpert.Vet
alias PetClinic.PetClinicService.ExpertSpecialities
alias PetClinic.AppoinmentService.Appointments
alias PetClinic.AppoinmentService.ExpertSchedule
alias PetClinic.AppointmentService.AppointmentService
alias PetClinic.PetClinicService.PetType

import_if_available(Ecto.Changeset)
import_if_available(Ecto.Query)
